test_matches = $(if $(findstring $1,$2),$(findstring $1,$2),$(if $1,,PASS))
test_func = $(call $(if $(call test_matches,$2,$(call $1,$3)),info,warning),$(if $(call test_matches,$2,$(call $1,$3)),PASS,FAIL) $1 | given: $3 | expected: $2 | evaluated: $(call $1,$3))
test_func2 = $(call $(if $(call test_matches,$2,$(call $1,$3,$4)),info,warning),$(if $(call test_matches,$2,$(call $1,$3,$4)),PASS,FAIL) $1 | given: $3,$4 | expected: $2 | evaluated: $(call $1,$3,$4))

maketest:
	$(call test_func,tail,dog pig,cat dog pig)

	$(call test_func,split_path,cat dog pig,cat/dog/pig)
	$(call test_func,split_path,cat dog pig,cat/dog/pig/)
	$(call test_func,split_path,$(_root_standin) cat dog pig,/cat/dog/pig/)
	$(call test_func,split_path,$(_root_standin) common prefix,/common/prefix/cat)
	$(call test_func,split_path,$(_root_standin) common prefix,/common/prefix/cat.txt)

	$(call test_func,join_path,joined,joined)
	$(call test_func,join_path,joined/path,joined path)
	$(call test_func,join_path,joined/path/parts,joined path parts)
	$(call test_func,join_path,/joined/path/parts,$(_root_standin) joined path parts)

	$(call test_func2,common_prefix_impl,,uncommon prefix cat.txt,common prefix for dog.txt)
	$(call test_func2,common_prefix_impl,common prefix,common prefix cat.txt,common prefix for dog.txt)
	$(call test_func2,common_prefix_impl,$(_root_standin) common prefix,$(_root_standin) common prefix cat.txt,$(_root_standin) common prefix for dog.txt)
	$(call test_func2,common_prefix,common/prefix,common/prefix/cat.txt,common/prefix/for/dog.txt)
	$(call test_func2,common_prefix_impl,$(_root_standin) common prefix,$(call split_path,/common/prefix/cat.txt),$(call split_path,/common/prefix/for/dog.txt))
	$(call test_func2,common_prefix,/common/prefix,/common/prefix/cat.txt,/common/prefix/for/dog.txt)
	$(call test_func2,common_prefix,/common/prefix,/common/prefix,/common/prefix/for/dog.txt)
	$(call test_func2,common_prefix,/common/prefix,/common/prefix/for/dog.txt,/common/prefix)
	$(call test_func2,common_prefix,/prefix,/prefix/cat.txt,/prefix)

	$(call test_func2,remove_prefix,dog,path/to/cat,path/to/cat/dog)
	$(call test_func2,remove_prefix,dog,path/to/cat/,path/to/cat/dog)
	$(call test_func2,remove_prefix,,path/to/cat/,path/to/cat/)
	$(call test_func2,remove_prefix,,path/to/cat,path/to/cat)
	$(call test_func2,remove_prefix,,$(call common_prefix,/common/prefix/for/cat.txt,/common/prefix),/common/prefix)

	$(call test_func,make_relative_prefix,,)
	$(call test_func,make_relative_prefix,../..,common/prefix)
	$(call test_func,make_relative_prefix,../../..,/common/prefix)

	$(call test_func2,relative_path,../cat.txt,common/prefix/cat.txt,common/prefix/for/dog.txt)
	$(call test_func2,relative_path,../../cat.txt,common/prefix/cat.txt,common/prefix/for/path/dog.txt)
	$(call test_func2,relative_path,../../cat.txt,/common/prefix/cat.txt,/common/prefix/for/path/dog.txt)
	$(call test_func2,relative_path,../for/cat.txt,/common/prefix/for/cat.txt,/common/prefix/dog.txt)
	$(call test_func2,relative_path,../../for/cat.txt,/common/prefix/for/cat.txt,/common/prefix/to/dog.txt)
	$(call test_func2,relative_path,cat.txt,/prefix/cat.txt,/prefix)
	$(call test_func2,relative_path,for/cat.txt,/common/prefix/for/cat.txt,/common/prefix)
	$(call test_func2,relative_path,branch,$(ROOT_DIR)/branch,$(ROOT_DIR))

	$(call test_func,get_module_obj_dir,$(OBJ_ROOT)/modules/branch,branch)
	$(call test_func,get_module_obj_dir,$(OBJ_ROOT)/modules/externUPdir_UPdir/branch,../../branch)

	$(call test_func,get_module_src_dir,branch,$(OBJ_ROOT)/modules/branch)
	$(call test_func,get_module_src_dir,../../branch,$(OBJ_ROOT)/modules/externUPdir_UPdir/branch)
